server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    # Správný typ pro manifest (přidání appky na plochu mobilu)
    location = /manifest.json {
        default_type application/manifest+json;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
